### ISSUE TITLE
Problems trying to reconnect to WIFI using NVS

### ISSUE THREAD

**Issue by otavioonoue** [ivmarkov/esp-idf-svc#304]
Good afternoon!

A few months ago I was trying to resolve an error that persists when using another NVS partition and the Wifi does not reconnect automatically. Only working after a manual reboot.
I'm using the standard Esp libs, following similar to the lib examples folder.

`
I (8345) wifi:new:<11,2>, old:<1,0>, ap:<255,255>, sta:<11,2>, prof:1
I (9095) wifi:state: init -> auth (b0)
I (9095) wifi:state: auth -> init (8a0)
I (9095) wifi:new:<11,0>, old:<11,2>, ap:<255,255>, sta:<11,2>, prof:1
`

Problem above.

I would appreciate any possible advice on how to solve this problem.

Thanks!

**Comment by Vollbrecht** [comment]
Well i think with the information you gave, one cant really help here. First why do you think the NVS has anything to do with your problem? And you are talking about few months ago? What does that mean? You are using esp-idf-* versions from a view months ago?  You need to give some more information about your complete setup, what esp-idf versions are you using, how you assemble your project with regarding to wifi etc. Without that i think there is nothing really what others can help here if you are that vague.

**Comment by ivmarkov** [comment]
Can you paste a short code snippet please which outlines what is supposed to work and doesn't? As in what methods exactly you are calling of the Wifi driver?

**Comment by Vollbrecht** [comment]
its not good practice to just use core::mem::forget on an object you want to possible use on the complete lifetime of your app. 

Also note that the wifi example itself is only a basic setup. If you want to react on different states your wifi might be in, it is always recommended to listen to the specific wifi-events and act on them. You can find all wifi-events [here](https://github.com/esp-rs/esp-idf-svc/blob/master/src/wifi.rs#L1589). You can subscribe to this events through the sysloop.subscribe() method. 

It looks rougly like that:
```rust
        
        sysloop.subscribe::<WifiEvent>(move |event| {
           if *event == WifiEvent::<SPECIFIC WIFI EVENT VARIANT>{
                // your event handling code
             }

```

you can get more fancy than that, using other eventloop mechanisms  / notifications. But this will let you react on things on runetime. If you are in an undesirable state you can try to force a new connection or just reboot or do whatever to handle it. 

Also if you are not using an async runtime / executor, try to use normal blocking rust calls to make your life easier at this stage.

**Comment by Vollbrecht** [comment]
For an overall overview check out the official [esp-idf](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html) documentation. Keep in mind that there are many EspWifi Events. You can find out what emits specific events by searching for "wifi_event" inside that linked documentation. You should not blindly just reboot on any wifievent you get that is not StaConnected.

**Comment by MG-96** [comment]
Hello, 
I am facing a similar behaviour where I get the same log messages as @Ott-cop  when using wifi.

For me this behaviour seems to be triggered whenever the system resets while connected to a network.
I noticed it whenever I flashed the device and had it connected to wifi already (as its common when coding).
A ctrl-r reset in espflash monitor or a complete powercycle helps.

I noticed this across multiple projects utilizing the esp32c3 which use more or less the stock blocking wifi example with some gpio (spi, ...) and mqtt functionality added.

I haven't validated that this happens when the connection drops out, but had some devices randomly stuck at the connect step without a manual reset (probably my code panicked when the connection dropped and thus had a soft reset).

To be complete, following are the relevant dependencies and idf versions I use:
```
esp-idf-sys = { version = "0.33", default-features = false }
esp-idf-hal = { version = "0.41", optional = true, default-features = false }
esp-idf-svc = { version = "0.46", optional = true, default-features = false }
embedded-svc = { version = "0.25", optional = true, default-features = false }
embedded-hal = "1.0.0-alpha.10"
```
```
ESP_IDF_VERSION = "v4.4.5"
```

**Comment by vojty** [comment]
I have a possibly related problem. The very first `wifi.connect()` (either after flashing or once I plug it into the power supply) fails and it always goes like this:
```
I (4094) wifi:state: init -> auth (b0)
I (4094) wifi:state: auth -> init (8a0)
```
The problem occurs both with and without NVS. The reset button or CTRL+R always fixes this. This didn't happen before with ESP-IDF v4. The same problem appears when the connection is lost so the following code for reconnecting didn't work:
```rs
    sysloop.subscribe(move |parsed_event: &WifiEvent| {
        if *parsed_event == WifiEvent::StaDisconnected {
            wifi.connect.unwrap();
        }
    })?;
```

I ended up with this hack, that works for both the initial connect and the reconnect:
```rs
pub trait WifiConnectFix {
    fn connect_with_retry(&mut self, retry_delay_ms: u64) -> anyhow::Result<()>;
}

pub fn sleep_ms(ms: u64) {
    thread::sleep(Duration::from_millis(ms));
}

impl WifiConnectFix for BlockingWifi<EspWifi<'_>> {
    fn connect_with_retry(&mut self, retry_delay_ms: u64) -> anyhow::Result<()> {
        loop {
            info!("Connecting wifi...");
            match self.connect() {
                Ok(()) => break,
                Err(e) => {
                    warn!(
                        "Wifi connect failed, reason {}, retrying in {}s",
                        e,
                        retry_delay_ms / 1000
                    );
                    sleep_ms(retry_delay_ms);
                    self.stop()?;
                    self.start()?;
                }
            }
        }

        info!("Waiting for DHCP lease...");

        self.wait_netif_up()?;
        Ok(())
    }
}
```

I'm using ESP-IDF `v5.1.2` with these crates:
```toml
[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
embedded-hal = "0.2.7"
embedded-svc= "0.26.2"
esp-idf-svc = "0.47.3"
log = "0.4.20"

[build-dependencies]
dotenv-build = "0.1.1"
embuild = "0.31.4"
```

**Comment by embediver** [comment]
I observed the behaviour a little further and noticed this bug isn't consistent across different wifi networks.

As far as I can tell without testing it thoroughly, it works without problems on some networks, but has problems on other ones. (I have problems on my home network but not on the local hackerspaces network for example.)

**Comment by archifo** [comment]
Hi,
I have a question related to the title of this thread but different from its contents.
I implement a very simple use case for wifi initialization :
1/ Attempt to connect to the Access Point which has been stored in NVS during the last boot session
2/ If unsuccessful, launch a SmartConfig session, waiting for my smartphone to provide the ssid and password with an ESP Touch app.
This is straightforward using the Arduino framework, especially phase 1  which consists of calling "Wifi.begin(), the equivalent of the Rust sequence init, start, connect, without argument instead of (ssid, password).
I tried in Rust to connect without calling set_configuration or calling it with empty SSID/PASS values, but it fails with an EspErrWifiSsid error.
Any idea to solve my problem ?

**Comment by ivmarkov** [comment]
Folks, can you try with `esp-idf-svc` from `master`?
I just fixed it to be compatible with ESP-IDF 5.3, but **ALSO** I noticed that two parameters in the Wifi configuration which existed before ESP IDF 5.3 were missing (incorrectly configured). This is now fixed as well.

**Comment by vojty** [comment]
FYI In my case, this problem disappeared once I bought a new router (TP-Link Archer AX72 Pro)

**Comment by giomf** [comment]
> > Unfortunately, even master doesn't fix the problem for me. I still get the following log output:
> > ```
> > I (3057) wifi:new:<6,0>, old:<1,0>, ap:<255,255>, sta:<6,0>, prof:1
> > I (3057) wifi:state: init -> auth (b0)
> > I (7347) wifi:state: auth -> init (200)
> > I (7347) wifi:new:<6,0>, old:<6,0>, ap:<255,255>, sta:<6,0>, prof:1
> > ```
> 
> How are you using `master`? You sure you have set it up correctly?

I'm not entirely sure. I actually only specified the github link in my Cargo.toml and set branch to master. Is that correct?

**Comment by ivmarkov** [comment]
> > > Unfortunately, even master doesn't fix the problem for me. I still get the following log output:
> > > ```
> > > I (3057) wifi:new:<6,0>, old:<1,0>, ap:<255,255>, sta:<6,0>, prof:1
> > > I (3057) wifi:state: init -> auth (b0)
> > > I (7347) wifi:state: auth -> init (200)
> > > I (7347) wifi:new:<6,0>, old:<6,0>, ap:<255,255>, sta:<6,0>, prof:1
> > > ```
> > 
> > 
> > How are you using `master`? You sure you have set it up correctly?
> 
> I'm not entirely sure. I actually only specified the github link in my Cargo.toml and set branch to master. Is that correct?

You need to show the relevant part of `Cargo.toml`.

**Comment by giomf** [comment]
Yes of course.

`esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc.git", branch = "master", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
`
But im running into an error now:
`the package `esp-idf-svc` depends on `esp-idf-hal`, with features: `experimental` but `esp-idf-hal` does not have these features`

Deactivating the features lets it build but I think that this is not intended.

**Comment by ivmarkov** [comment]
No not this way. Revert to the released versions and then add this to your `Cargo.toml`:
```toml
[patch.crates-io]
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal" }
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys" }
cmake = { git = "https://github.com/ivmarkov/cmake-rs" }
```

**Comment by giomf** [comment]
Thanks! It seems to resolve the error. Will have a closer look in future.

**Comment by turaib** [comment]
I have the same problem. I can't connect to my home Wi-Fi network with my ESP32-C3 module.

I also get an `ESP_ERR_TIMEOUT` error after trying to connect. The error persists regardless of whether NVS is passed as a parameter.

I tried turning off Wi-Fi power saving mode, modifying dependencies (applying patches), stopping and starting the Wi-Fi interface again. I reset the module, but none of these attempts solved the problem.

I was able to connect to the network with this module before, but now I can't.

Do you have any other suggestions that would be worth trying?

<table>
  <tr>
    <td colspan="2">Wi-Fi network:</td>
  </tr>
  <tr>
    <td>Auth mode:</td>
    <td>WPA2 PSK</td>
  </tr>
  <tr>
    <td>Channel:</td>
    <td>4</td>
  </tr>
  <tr>
    <td>Mode:</td>
    <td>802.11g/n/ax</td>
  </tr>
</table>



Cargo.toml:

```toml
[package]
name = "wifi_c3"
version = "0.1.0"
authors = ["---"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "wifi_dbg_c3"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = []

experimental = ["esp-idf-svc/experimental"]

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.51", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
anyhow = "1.0.97"

[build-dependencies]
embuild = "0.33"

```

config.toml

```toml
[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32c3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.3"
ESP_IDF_PATH_ISSUES = 'warn'
```

main.rs: 

```rust

fn main() -> anyhow::Result<()> {
    esp_idf_svc::sys::link_patches();
    esp_idf_svc::log::EspLogger::initialize_default();
    let peripherals = Peripherals::take()?;
    let sys_loop = EspSystemEventLoop::take()?;
    let nvs = EspDefaultNvsPartition::take()?;
    let mut esp_wifi = EspWifi::new(peripherals.modem, sys_loop.clone(), Some(nvs))?;
    let mut wifi = BlockingWifi::wrap(&mut esp_wifi, sys_loop.clone())?;

    unsafe { esp_idf_svc::sys::esp_wifi_set_ps(esp_idf_svc::sys::wifi_ps_type_t_WIFI_PS_NONE); }

    wifi.set_configuration(&Configuration::Client(ClientConfiguration {
        ssid: SSID.try_into().unwrap(),
        password: PASSWORD.try_into().unwrap(),
        auth_method: AuthMethod::WPA2Personal,
        ..Default::default()
    }))?;

    wifi.start()?;
    for _ in 0..10 {
        match wifi.connect() {
            Ok(_) => break,
            Err(e) => error!("{:?}", e)
        }
    }

    loop{
        let ip_info = wifi.wifi().sta_netif().get_ip_info()?;
        log::info!("{:?}", ip_info);
        std::thread::sleep(std::time::Duration::from_secs(5));
    }
}

```


sdkconfig.defaults:

```
CONFIG_ESP_MAIN_TASK_STACK_SIZE=20000
CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE=4096
```
